-- usign SERIAL

CREATE TABLE users (
	"user_id" SERIAL PRIMARY KEY,
	"username" VARCHAR(50)
);

-- usign IDENTIY similate by SERIAL
CREATE TABLE users(
	"user_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	"username" VARCHAR(50)
);


-- It does not allow entering values in the primary key column
CREATE TABLE users (
	"user_id" INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	"username" VARCHAR(50)
);

-- START WITH 100 AND INCREMENT BY 2
CREATE TABLE users(
	"user_id" INTEGER GENERATED ALWAYS AS IDENTITY (START WITH 100 INCREMENT BY 2),
	"username" VARCHAR(30)
);

-- mixed primary keys
CREATE TABLE users_dual(
	id1 int,
	id2 int,
	PRIMARY KEY(id1, id2)
);