-- usign SERIAL

CREATE TABLE users (
	"user_id" SERIAL PRIMARY KEY,
	"username" VARCHAR(50)
);

-- usign IDENTIY similate by SERIAL
CREATE TABLE users(
	"user_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	"username" VARCHAR(50)
);


-- It does not allow entering values in the primary key column
CREATE TABLE users (
	"user_id" INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	"username" VARCHAR(50)
);

-- START WITH 100 AND INCREMENT BY 2
CREATE TABLE users(
	"user_id" INTEGER GENERATED ALWAYS AS IDENTITY (START WITH 100 INCREMENT BY 2),
	"username" VARCHAR(30)
);

-- mixed primary keys
CREATE TABLE users_dual(
	id1 int,
	id2 int,
	PRIMARY KEY(id1, id2)
);

--gen_random_uuid
SELECT gen_random_uuid();

-- Install extension uuid-ossp
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

SELECT gen_random_uuid(), uuid_generate_v4();

-- UUIDs
CREATE TABLE users(
	"user_id" UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
	"username" VARCHAR
);

-- sequence
DROP SEQUENCE user_sequence;
CREATE SEQUENCE user_sequence;

select currval('user_sequence'), nextval('user_sequence'), currval('user_sequence')

CREATE TABLE users(
	"user_id" INTEGER PRIMARY KEY DEFAULT nextval('user_sequence'),
	"username" VARCHAR(10)
);